const SUBMIT_CUSTOM_FORM_REQUEST = "SUBMIT_CUSTOM_FORM_REQUEST";
const SUBMIT_CUSTOM_FORM_SUCCESS = "SUBMIT_CUSTOM_FORM_SUCCESS";
const SUBMIT_CUSTOM_FORM_FAILURE = "SUBMIT_CUSTOM_FORM_FAILURE";
const CREATE_CUSTOM_FORM_REQUEST = "SUBMIT_CUSTOM_FORM_REQUEST";
const CREATE_CUSTOM_FORM_SUCCESS = "SUBMIT_CUSTOM_FORM_SUCCESS";
const CREATE_CUSTOM_FORM_FAILURE = "SUBMIT_CUSTOM_FORM_FAILURE";
const SHOW_FIRST_CUSTOM_FORM = "SHOW_FIRST_CUSTOM_FORM";
const GET_QUESTIONNAIRE_REQUEST = "GET_QUESTIONNAIRE_REQUEST";
const GET_QUESTIONNAIRE_SUCCESS = "GET_QUESTIONNAIRE_SUCCESS";
const GET_QUESTIONNAIRE_FAILURE = "GET_QUESTIONNAIRE_FAILURE";
const SUBMIT_QUESTIONNAIRE_FORM_REQUEST = "SUBMIT_QUESTIONNAIRE_FORM_REQUEST";
const SUBMIT_QUESTIONNAIRE_FORM_SUCCESS = "SUBMIT_QUESTIONNAIRE_FORM_SUCCESS";
const SUBMIT_QUESTIONNAIRE_FORM_FAILURE = "SUBMIT_QUESTIONNAIRE_FORM_FAILURE";

export {
    SUBMIT_CUSTOM_FORM_REQUEST,
    SUBMIT_CUSTOM_FORM_SUCCESS,
    SUBMIT_CUSTOM_FORM_FAILURE,
    CREATE_CUSTOM_FORM_REQUEST,
    CREATE_CUSTOM_FORM_SUCCESS,
    CREATE_CUSTOM_FORM_FAILURE,
    SHOW_FIRST_CUSTOM_FORM,
    GET_QUESTIONNAIRE_REQUEST,
    GET_QUESTIONNAIRE_SUCCESS,
    GET_QUESTIONNAIRE_FAILURE,
    SUBMIT_QUESTIONNAIRE_FORM_REQUEST,
    SUBMIT_QUESTIONNAIRE_FORM_SUCCESS,
    SUBMIT_QUESTIONNAIRE_FORM_FAILURE
}