const SUBMIT_PATCH_ORDER_REQUEST = "SUBMIT_PATCH_ORDER_REQUEST";
const SUBMIT_PATCH_ORDER_SUCCESS = "SUBMIT_PATCH_ORDER_SUCCESS";
const SUBMIT_PATCH_ORDER_FAILURE = "SUBMIT_PATCH_ORDER_FAILURE";

export {
    SUBMIT_PATCH_ORDER_REQUEST,
    SUBMIT_PATCH_ORDER_SUCCESS,
    SUBMIT_PATCH_ORDER_FAILURE,
}