const SUBMIT_PATIENT_FORM_REQUEST = "SUBMIT_CUSTOM_FORM_REQUEST";
const SUBMIT_PATIENT_FORM_SUCCESS = "SUBMIT_CUSTOM_FORM_SUCCESS";
const SUBMIT_PATIENT_FORM_FAILURE = "SUBMIT_CUSTOM_FORM_FAILURE";
const GET_PATIENT_REQUEST = "GET_PATIENT_REQUEST";
const GET_PATIENT_SUCCESS = "GET_PATIENT_SUCCESS";
const GET_PATIENT_FAILURE = "GET_PATIENT_FAILURE";

export {
    SUBMIT_PATIENT_FORM_REQUEST,
    SUBMIT_PATIENT_FORM_SUCCESS,
    SUBMIT_PATIENT_FORM_FAILURE,
    GET_PATIENT_REQUEST,
    GET_PATIENT_SUCCESS,
    GET_PATIENT_FAILURE,
}